"""Ideal 4-qubit QAOA code for the Max-Cut problem only.

Package installation:
    pip install qiskit numpy qiskit-aer qiskit-ibm-runtime
or
    python -m pip install qiskit numpy qiskit-aer qiskit-ibm-runtime

Imported libraries:
    - itertools: brute-force classical reference search
    - math: pi range for the parameter grid
    - time: runtime measurement
    - dataclasses: compact result container
    - numpy: parameter grids and numeric evaluation
    - qiskit.QuantumCircuit: logical circuit construction
    - qiskit.qasm2.dumps: ASCII-safe circuit export
    - qiskit.quantum_info.SparsePauliOp: Max-Cut Hamiltonian
    - qiskit.quantum_info.Statevector: exact ideal expectation evaluation

This script:
    1. Defines a fixed 4-node Max-Cut graph.
    2. Builds the QAOA p=1 ansatz for that graph.
    3. Builds the Max-Cut Hamiltonian H_C.
    4. Searches over (gamma, beta) on a grid.
    5. Evaluates <H_C> exactly using the ideal statevector.
    6. Prints the best logical circuit and total runtime.
"""

from __future__ import annotations

import itertools
import math
import time
from dataclasses import dataclass
from typing import Sequence

import numpy as np
from qiskit import QuantumCircuit
from qiskit.qasm2 import dumps
from qiskit.quantum_info import SparsePauliOp, Statevector


Edge = tuple[int, int]
NUM_QUBITS = 4
EDGES: list[Edge] = [(0, 1), (1, 2), (2, 3), (3, 0)]
MAX_CLASSICAL_CUT = 4


@dataclass(frozen=True)
class SearchResult:
    """Container for the best p=1 QAOA parameters found by grid search."""

    gamma: float
    beta: float
    expectation: float
    approximation_ratio: float
    most_likely_bitstring: str
    most_likely_bitstring_cut: int


def maxcut_cost(bitstring: str, edges: Sequence[Edge] = EDGES) -> int:
    """Return the Max-Cut objective value for a measured bitstring.

    The Hamiltonian and circuit are built in Qiskit's qubit order. Measurement
    strings are displayed as q_(n-1)...q_0, so the string is reversed before
    indexing by qubit number.
    """
    bits = bitstring[::-1]
    return sum(1 for i, j in edges if bits[i] != bits[j])


def brute_force_solutions(
    num_qubits: int = NUM_QUBITS,
    edges: Sequence[Edge] = EDGES,
) -> tuple[int, list[str]]:
    """Compute the exact classical Max-Cut optimum by exhaustive search."""
    best_value = -1
    best_bitstrings: list[str] = []

    for bits in itertools.product("01", repeat=num_qubits):
        bitstring = "".join(bits)
        cut_value = maxcut_cost(bitstring, edges)
        if cut_value > best_value:
            best_value = cut_value
            best_bitstrings = [bitstring]
        elif cut_value == best_value:
            best_bitstrings.append(bitstring)

    return best_value, best_bitstrings


def maxcut_hamiltonian(
    num_qubits: int = NUM_QUBITS,
    edges: Sequence[Edge] = EDGES,
) -> SparsePauliOp:
    """Construct H_C = sum_(i,j in E) 1/2 (I - Z_i Z_j) for Max-Cut."""
    pauli_terms: list[tuple[str, float]] = [("I" * num_qubits, 0.5 * len(edges))]

    for i, j in edges:
        label = ["I"] * num_qubits
        label[num_qubits - 1 - i] = "Z"
        label[num_qubits - 1 - j] = "Z"
        pauli_terms.append(("".join(label), -0.5))

    return SparsePauliOp.from_list(pauli_terms)


def build_qaoa_circuit(
    gamma: float,
    beta: float,
    num_qubits: int = NUM_QUBITS,
    edges: Sequence[Edge] = EDGES,
    measure: bool = False,
) -> QuantumCircuit:
    """Build the p=1 logical QAOA circuit for 4-qubit Max-Cut.

    The ansatz is
        |psi(gamma, beta)> = exp(-i beta H_B) exp(-i gamma H_C) |+>^⊗n

    where
        H_C = sum_(i,j in E) 1/2 (I - Z_i Z_j)
        H_B = sum_i X_i

    For each edge (i, j), the cost unitary contribution is implemented with
    a CNOT-RZ-CNOT pattern. For each qubit, the mixer is RX(2 beta).
    """
    circuit = QuantumCircuit(num_qubits, num_qubits if measure else 0)

    # Prepare the uniform superposition |+>^⊗4.
    circuit.h(range(num_qubits))
    circuit.barrier(label="init")

    # Apply the phase-separation unitary generated by the Max-Cut Hamiltonian.
    for control, target in edges:
        circuit.cx(control, target)
        circuit.rz(-gamma, target)
        circuit.cx(control, target)
    circuit.barrier(label="cost")

    # Apply the mixer unitary generated by H_B = sum_i X_i.
    for qubit in range(num_qubits):
        circuit.rx(2.0 * beta, qubit)
    circuit.barrier(label="mixer")

    if measure:
        circuit.measure(range(num_qubits), range(num_qubits))

    return circuit


def expectation_value(
    circuit: QuantumCircuit,
    hamiltonian: SparsePauliOp | None = None,
) -> float:
    """Compute the exact ideal value <psi|H_C|psi> from the statevector."""
    observable = hamiltonian or maxcut_hamiltonian(circuit.num_qubits)
    state = Statevector.from_instruction(circuit)
    return float(np.real(state.expectation_value(observable)))


def statevector_mode(circuit: QuantumCircuit, edges: Sequence[Edge] = EDGES) -> tuple[str, int]:
    """Return the highest-probability basis state and its Max-Cut value."""
    probabilities = Statevector.from_instruction(circuit).probabilities_dict()
    bitstring = max(probabilities, key=probabilities.get)
    return bitstring, maxcut_cost(bitstring, edges)


def find_best_qaoa_parameters(
    gamma_points: int = 41,
    beta_points: int = 41,
    num_qubits: int = NUM_QUBITS,
    edges: Sequence[Edge] = EDGES,
) -> SearchResult:
    """Grid-search p=1 QAOA parameters for the 4-qubit Max-Cut instance.

    Search domain:
        gamma in [0, pi]
        beta  in [0, pi/2]
    """
    hamiltonian = maxcut_hamiltonian(num_qubits, edges)
    best_result = SearchResult(
        gamma=0.0,
        beta=0.0,
        expectation=float("-inf"),
        approximation_ratio=0.0,
        most_likely_bitstring="0" * num_qubits,
        most_likely_bitstring_cut=0,
    )

    for gamma in np.linspace(0.0, math.pi, gamma_points):
        for beta in np.linspace(0.0, math.pi / 2.0, beta_points):
            circuit = build_qaoa_circuit(float(gamma), float(beta), num_qubits, edges, measure=False)
            expectation = expectation_value(circuit, hamiltonian)
            if expectation > best_result.expectation:
                mode_bitstring, mode_cut = statevector_mode(circuit, edges)
                best_result = SearchResult(
                    gamma=float(gamma),
                    beta=float(beta),
                    expectation=expectation,
                    approximation_ratio=expectation / MAX_CLASSICAL_CUT,
                    most_likely_bitstring=mode_bitstring,
                    most_likely_bitstring_cut=mode_cut,
                )

    return best_result


def qasm_output(circuit: QuantumCircuit) -> str:
    """Return an ASCII-safe OpenQASM representation of the circuit."""
    return dumps(circuit)


def main() -> None:
    start_time = time.perf_counter()

    classical_cut, classical_solutions = brute_force_solutions()
    best_result = find_best_qaoa_parameters()
    measured_circuit = build_qaoa_circuit(best_result.gamma, best_result.beta, measure=True)

    elapsed = time.perf_counter() - start_time

    print("=== Package installation ===")
    print("pip install qiskit numpy qiskit-aer qiskit-ibm-runtime")
    print()

    print("=== 4-Qubit Max-Cut instance ===")
    print(f"Number of qubits: {NUM_QUBITS}")
    print(f"Edges: {EDGES}")
    print()

    print("=== Classical Max-Cut reference ===")
    print(f"Maximum cut value: {classical_cut}")
    print(f"Optimal bitstrings: {classical_solutions}")
    print()

    print("=== Ideal QAOA result (p=1) ===")
    print(f"Best gamma: {best_result.gamma:.6f}")
    print(f"Best beta:  {best_result.beta:.6f}")
    print(f"Ideal expectation <H_C>: {best_result.expectation:.6f}")
    print(f"Approximation ratio:     {best_result.approximation_ratio:.6f}")
    print(f"Most likely bitstring:   {best_result.most_likely_bitstring}")
    print(f"Its cut value:           {best_result.most_likely_bitstring_cut}")
    print()

    print("=== Measured ideal circuit (OpenQASM) ===")
    print(qasm_output(measured_circuit))
    print()
    print(f"Depth: {measured_circuit.depth()}")
    print(f"Size: {measured_circuit.size()}")
    print(f"Operation counts: {dict(measured_circuit.count_ops())}")
    print()
    print(f"Runtime (seconds): {elapsed:.6f}")


if __name__ == "__main__":
    main()
